// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';
import { resolveBaseApiUrl } from './resolve-base-api-url';

export const environment = {
  production: true,
  version: env.mifos_x_version,
  fineractPlatformTenantId: 'default',  // Institutional tenant — replace for production deploys
  /**
   * Locked API host for production (SEC-03). Replace with your Fineract origin before deploy.
   * localStorage overrides are ignored when production === true.
   */
  baseApiUrl: 'https://demo.fineract.dev',
  allowServerSwitch: false,
  apiProvider: '/fineract-provider/api',
  apiVersion: '/v1',
  serverUrl: '',
  oauth: {
    enabled: false,
    serverUrl: '',
    clientId: 'community-app',
    /** Never ship a confidential client secret in production SPA builds (SEC-02). */
    clientSecret: ''
  },
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};

environment.baseApiUrl = resolveBaseApiUrl(environment.baseApiUrl, {
  production: environment.production,
  allowServerSwitch: environment.allowServerSwitch
});

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
